"""initial

Revision ID: 9d56c03d314f
Revises: 
Create Date: 2026-09-16 01:08:44.459073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d56c03d314f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camadas_geo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('geojson', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('estabelecimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('unidades_especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_id', 'especialidade_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('entidade', sa.String(length=80), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=120), nullable=False),
    sa.Column('dados', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('origem', sa.Enum('ouvidoria', 'excepcional', 'sei', 'programacao', name='origem_os'), nullable=False),
    sa.Column('tema', sa.String(length=200), nullable=False),
    sa.Column('ra', sa.String(length=80), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('raio_geo', sa.Numeric(precision=8, scale=1), nullable=False),
    sa.Column('prazo_data', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('rascunho', 'criada', 'vinculada', 'em_execucao', 'devolvida', 'concluida', 'arquivada', 'desarquivada', 'cancelada', name='status_os'), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('vinculos_funcionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acoes_fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('auto_infracao', 'notificacao', 'relatorio_tecnico', 'interdicao', 'apreensao', 'outro', name='tipo_acao'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('os_frentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('os_id', 'especialidade_id')
    )
    op.create_table('autos_infracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('natureza', sa.String(length=200), nullable=False),
    sa.Column('item_legislacao', sa.String(length=200), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('prazo_pagamento', sa.Date(), nullable=True),
    sa.Column('prazo_recurso', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('lavrado', 'encaminhado', 'julgado', 'anulado', 'arquivado', name='status_ai'), nullable=False),
    sa.Column('status_tributario', sa.Enum('pendente', 'enviado', 'pago', 'nao_pago', 'cancelado', name='status_tributario'), nullable=False),
    sa.Column('reincidente', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acao_id'], ['acoes_fiscais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acao_id')
    )
    op.create_table('os_auditores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('frente_id', sa.Integer(), nullable=True),
    sa.Column('atribuido_por_id', sa.Integer(), nullable=False),
    sa.Column('data_atribuicao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['atribuido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['frente_id'], ['os_frentes.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('os_id', 'usuario_id', 'frente_id')
    )
    op.create_table('reincidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('natureza', sa.String(length=200), nullable=False),
    sa.Column('numero_ocorrencia', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_id'], ['autos_infracao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reincidencias')
    op.drop_table('os_auditores')
    op.drop_table('autos_infracao')
    op.drop_table('os_frentes')
    op.drop_table('acoes_fiscais')
    op.drop_table('vinculos_funcionais')
    op.drop_table('ordens_servico')
    op.drop_table('log_auditoria')
    op.drop_table('usuarios')
    op.drop_table('unidades_especialidades')
    op.drop_table('unidades')
    op.drop_table('perfis')
    op.drop_table('estabelecimentos')
    op.drop_table('especialidades')
    op.drop_table('camadas_geo')
    # ### end Alembic commands ###