"""unique sigla per parent unit

Revision ID: eed8151c2634
Revises: b3e9c2a1d4f7
Create Date: 2026-09-21 17:07:16.869888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eed8151c2634'
down_revision: Union[str, None] = 'b3e9c2a1d4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_acoes_codigo_documento'), table_name='acoes_fiscais')
    op.drop_index(op.f('ix_itens_apreensao_acao_id'), table_name='itens_apreensao')
    op.drop_index(op.f('ix_log_auditoria_criado_em'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_entidade'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_usuario_id'), table_name='log_auditoria')
    op.drop_index(op.f('uq_ordens_servico_codigo'), table_name='ordens_servico')
    op.create_unique_constraint(None, 'ordens_servico', ['codigo'])
    op.drop_index(op.f('ix_tramites_acao_id'), table_name='tramites')
    op.drop_index(op.f('ix_tramites_criado_em'), table_name='tramites')
    op.drop_constraint(op.f('unidades_sigla_key'), 'unidades', type_='unique')
    op.create_unique_constraint('ux_unidades_sigla_pai', 'unidades', ['sigla', 'unidade_pai_id'])
    op.drop_index(op.f('ix_usuarios_orgao_id'), table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usuarios_orgao_id'), 'usuarios', ['orgao_id'], unique=False)
    op.drop_constraint('ux_unidades_sigla_pai', 'unidades', type_='unique')
    op.create_unique_constraint(op.f('unidades_sigla_key'), 'unidades', ['sigla'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tramites_criado_em'), 'tramites', ['criado_em'], unique=False)
    op.create_index(op.f('ix_tramites_acao_id'), 'tramites', ['acao_id'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ordens_servico', type_='unique')
    op.create_index(op.f('uq_ordens_servico_codigo'), 'ordens_servico', ['codigo'], unique=True)
    op.create_index(op.f('ix_log_auditoria_usuario_id'), 'log_auditoria', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_log_auditoria_entidade'), 'log_auditoria', ['entidade'], unique=False)
    op.create_index(op.f('ix_log_auditoria_criado_em'), 'log_auditoria', ['criado_em'], unique=False)
    op.create_index(op.f('ix_itens_apreensao_acao_id'), 'itens_apreensao', ['acao_id'], unique=False)
    op.create_index(op.f('uq_acoes_codigo_documento'), 'acoes_fiscais', ['codigo_documento'], unique=True)
    # ### end Alembic commands ###